In [2]:
import numpy as np

In [6]:
# 단위 행렬(항등 행렬)
a=np.eye(4)

In [7]:
# 생성된 배열의 데이터 타입 변경
a.astype("i")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [13]:
np.random.seed(0)
a=np.random.randint(0,2,9)
a.astype(bool).reshape(3,3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [16]:
np.random.seed(0)
a=np.random.rand(10)
a*=10
a.astype("i")

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [19]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
a=np.ones((10,10))
a[::9,:]=0
a[1:9,[0,9]]=0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
a=np.ones((8,8))
a[1::2,::2]=0
a[::2,1::2]=0
a


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [43]:
a=np.array([[1,0],[0,1]])
np.tile(a,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [53]:
a= np.arange(11)
b= np.array([True if 3< _<7 else False for _ in range(11)])
a[b]=-a[b]
a

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [56]:
np.array([ _ for _ in range(1,101) if _%3==0]).sum()

1683

In [58]:
np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
while True:
    try:
        n = int(input())
        if n > 0:
            break
        else:
            print("자연수만 입력해주세요")
    except:
        print("자연수만 입력해주세요")
l = []
for i in range(n):
    l.append(np.sort(np.random.choice(np.arange(1, 47), 6, replace = False)))
print(l)

 3


[array([ 2, 21, 23, 32, 33, 41]), array([17, 21, 32, 33, 35, 38]), array([ 6, 15, 18, 35, 38, 46])]


In [ ]:
while True:
    try:
        n = int(input())
        if n < 0:
            raise error
        break
    except:
        print("자연수만 입력해주세요")
l = [np.sort(np.random.choice(np.arange(1, 47), 6, replace = False)) for i in range(n)]
display(l)

 -1


자연수만 입력해주세요


In [10]:
l

[array([35, 17, 23,  3, 30, 28]),
 array([39, 28, 36, 13, 20, 25]),
 array([10, 11, 15, 37,  4,  5])]

In [5]:
n=None
n is None

True

In [2]:
import numpy as np
np.random.randint(1,3,6)

array([1, 1, 2, 2, 2, 1])

In [14]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])
np.percentile(resp_time,25)
np.percentile(esp_time,50)
np.percentile(resp_time,75)
np.percentile(resp_time,100)

175.5

In [20]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
a = np.bincount(result)
print(f"{p[a.argmax()]}가 {a.max()}표로 반장으로 선출되었습니다.")


뽀로로가 81표로 반장으로 선출되었습니다.


AttributeError: 'numpy.ndarray' object has no attribute 'unique'